# post_pkg_postinst is invoked by Portage after each package build/install
post_pkg_postinst() {
  # Load S3 credentials for use by rclone
  source /etc/portage/s3.sh

  # Locate the directory containing the newly built binary package
  directory=$(find /var/cache/binpkgs/ -maxdepth 1 -mindepth 1 -type d)
  directory_basename=$(basename $directory)

  # Upload the Packages file to the remote S3 bucket
  rclone --config /etc/portage/rclone.conf --s3-access-key-id $s3_access_key_id --s3-endpoint $s3_endpoint --s3-secret-access-key $s3_secret_access_key copy /var/cache/binpkgs/Packages 1:$s3_bucket

  # Upload the binary packages directory to the remote S3 bucket
  rclone --config /etc/portage/rclone.conf --s3-access-key-id $s3_access_key_id --s3-endpoint $s3_endpoint --s3-secret-access-key $s3_secret_access_key copy $directory 1:$s3_bucket:$directory_basename

  # Remove the local copy of the binary packages to free up space
  rm --recursive $directory
}
