# post_pkg_postinst is invoked by Portage after each package build/install
post_pkg_postinst() {
  # Load S3 credentials for use by rclone
  source /etc/portage/s3.sh

  # Upload the binary packages directory to the remote S3 bucket
  rclone --config /etc/portage/rclone.conf --s3-access-key-id $s3_access_key_id --s3-endpoint $s3_endpoint --s3-secret-access-key $s3_secret_access_key copy /tmp/upperdir 1:$s3_bucket

  # Remove the local copy of the binary packages to free up space
  rm --recursive /tmp/upperdir/*
}
