name: 1 Reconfigure

on:
  workflow_dispatch:

env:
  ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
  CONFIG_PREFIX: 1
#  EMERGE_PARAMETERS:
  STORAGE_ENDPOINT: ${{ secrets.STORAGE_ENDPOINT }}
  STORAGE_ZONE_NAME: ${{ secrets.STORAGE_ZONE_NAME }}

jobs:
  emerge:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Gentoo Environment
        run: |
          sudo --preserve-env bash -e -c '
            aria2c --dir=/mnt --header="AccessKey: $ACCESS_KEY" --header="accept: */*" https://$STORAGE_ENDPOINT/$STORAGE_ZONE_NAME/$CONFIG_PREFIX.tar.zstd
            mkdir /mnt/gentoo
            tar --directory=/mnt/gentoo --extract --file=/mnt/$CONFIG_PREFIX.tar.zstd --numeric-owner --preserve-permissions --xattrs-include="*.*"
            rm /mnt/$CONFIG_PREFIX.tar.zstd

            # Copy the locale configuration file
            cp ./$CONFIG_PREFIX/locale.gen /mnt/gentoo/etc

            # Copy the Portage configuration files
            rm --recursive /mnt/gentoo/etc/portage/env
            if [ -e /mnt/gentoo/etc/portage/package.env ]; then
              rm --recursive /mnt/gentoo/etc/portage/package.env
            fi
            rm --recursive /mnt/gentoo/etc/portage/package.use
            cp --recursive ./$CONFIG_PREFIX/portage /mnt/gentoo/etc
            cp ./$CONFIG_PREFIX/make-emerge.conf /mnt/gentoo/etc/portage/make.conf

            # Copy the ccache configuration file
            cp ./$CONFIG_PREFIX/ccache.conf /mnt/gentoo/etc

            # Copy the host'\''s DNS configuration into the chroot
            cp  /etc/resolv.conf /mnt/gentoo/etc
          '

      - name : Upload Gentoo Archive
        run: |
          sudo --preserve-env bash -e -c '
            # Create a tarball of the Gentoo environment
            tar --create --directory=/mnt/gentoo --file=/mnt/$CONFIG_PREFIX.tar.zst --numeric-owner --preserve-permissions --use-compress-program="zstd -T8 --fast --long=31" --xattrs-include="*.*" .
            echo "Gentoo archive created"
            curl --header "accept: application/json" --header "accesskey: $ACCESS_KEY" --header "content-type: application/octet-stream" --silent --upload-file /mnt/$CONFIG_PREFIX.tar.zst --url https://$STORAGE_ENDPOINT/$STORAGE_ZONE_NAME/
          '
