name: 1 Reconfigure

on:
  workflow_dispatch:

env:
  ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
  CONFIG_PREFIX: 1
  EMERGE_PARAMETERS: dev-util/ccache
  STORAGE_ENDPOINT: ${{ secrets.STORAGE_ENDPOINT }}
  STORAGE_ZONE_NAME: ${{ secrets.STORAGE_ZONE_NAME }}

jobs:
  emerge:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
